name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Validate test files
        run: |
          wget -O test/OfficialTest.cpp https://raw.githubusercontent.com/GonzagaCPSC122/PA4StarterCode/master/test/Test.cpp; wget -O .github/classroom/official_autograding.json https://raw.githubusercontent.com/GonzagaCPSC122/PA4StarterCode/master/.github/classroom/autograding.json; if cmp "test/OfficialTest.cpp" "test/Test.cpp" && cmp ".github/classroom/official_autograding.json" ".github/classroom/autograding.json"; then echo "The files match"; exit 0; fi; echo "The files are different"; exit 1;
      - name: Test code
        if: always()
        uses: education/autograding@v1
      